trigger:
  branches:
    include:
      - Dev
  paths:
    exclude:
      - '*'
variables:
  Devozy_DUMMY_VARIABLE: ID_nuFSk7r1
  IMAGE_NAME: PLN1000002_MERN_Development
pool:
  vmImage: ubuntu-latest
steps:
  - task: PublishBuildArtifacts@1
    inputs:
      versionSpec: 22.15.0
    displayName: node
  - script: npm install --force
    displayName: npm
  - script: sudo tar -czvf pln1000002.tar.gz *;
    displayName: Create tar.gz Archive of Build Files
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)/pln1000002.tar.gz
      artifactName: react-build
