trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*'
variables:
  Devozy_DUMMY_VARIABLE: ID_jvBe9aAR
  IMAGE_NAME: PLN1000011_MERN_Development
pool:
  vmImage: ubuntu-latest
steps:
  - task: PublishBuildArtifacts@1
    inputs:
      versionSpec: 22.14.0
    displayName: node
  - script: npm install --force
    displayName: npm
  - script: sudo tar -czvf pln1000011.tar.gz  *;
    displayName: Create tar.gz Archive of Build Files
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)/pln1000011.tar.gz
      artifactName: react-build
