trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*'
variables:
  Devozy_DUMMY_VARIABLE: ID_8Hrd16ol
  IMAGE_NAME: PLN1000012_MERN_UAT
pool:
  vmImage: ubuntu-latest
steps:
  - task: PublishBuildArtifacts@1
    inputs:
      versionSpec: 22.14.0
    displayName: node
  - script: npm install --force
    displayName: npm
  - script: sudo tar -czvf pln1000012.tar.gz *;
    displayName: Create tar.gz Archive of Build Files
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(System.DefaultWorkingDirectory)/pln1000012.tar.gz
      artifactName: react-build
